[package]
name = "test_rs"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[features]
native-crypto = ["hex", "hex-literal"]

[dependencies]
rand = "0.8.4"
clap = "3.0.0-beta.4"
hex = { version = "0.4.3", optional = true }
hex-literal = { version = "0.3.3", optional = true }
