name: IOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -GXcode -DCMAKE_SYSTEM_NAME=iOS

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --target srtp3 -- -sdk iphonesimulator
